# -*- coding: utf-8 -*-
"""Importance of Arrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1noIZlh8Zx96tQlRyRp6A7Cl2asVOLDlA

#### Without Array
"""

student1 = "Alice"
student2 = "Bob"
student3 = "Charlie"

# What if you want to find "Bob"?
if student1 == "Bob":
    print("Found Bob in student1")
elif student2 == "Bob":
    print("Found Bob in student2")
elif student3 == "Bob":
    print("Found Bob in student3")
else:
    print("Bob not found")

"""#### With Array"""

# Define the list of students
students = ["Alice", "Bob", "Charlie"]

# Define the student to find
student_to_find = "Bob"

# Loop through the list to find the specific student
for index, student in enumerate(students):
    if student == student_to_find:
        print(f"Found {student_to_find} at index {index}")
        break
else:
    print(f"{student_to_find} not found in the list")

"""#### Another Example with More Students

Imagine we have 300 student names. Using individual variables would be impractical. With an array, we can easily manage and search through the list
"""

# Define a larger list of students
students = ["Alice", "Bob", "Charlie"] + [f"Student{i}" for i in range(4, 301)]

# Define the student to find
student_to_find = "Bob"

# Loop through the list to find the specific student
for index, student in enumerate(students):
    if student == student_to_find:
        print(f"Found {student_to_find} at index {index}")
        break
else:
    print(f"{student_to_find} not found in the list")