# -*- coding: utf-8 -*-
"""Understanding Index, Memory Address, Value in Array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P95YkGeExQwutRvENimzjQPpl3s4Fgd-
"""

arr = [3, 4, 7, 9, 7, 1]
print("Base address:- ", arr)
print("Element address at index 3:- ", id(arr[3]))

arr = [12, 25, 37, 49, 58, 61]

for index, value in enumerate(arr):
    print(f"Index: {index}, Memory Address: {id(value)}, Value: {value}")



"""#### Without Array
Using individual variables for each student's name:
"""

student1 = "Alice"
student2 = "Bob"
student3 = "Charlie"

# What if you want to find "Bob"?
if student1 == "Bob":
    print("Found Bob in student1")
elif student2 == "Bob":
    print("Found Bob in student2")
elif student3 == "Bob":
    print("Found Bob in student3")
else:
    print("Bob not found")

"""#### With Array"""

# Define the list of students
students = ["Alice", "Bob", "Charlie"]

# Define the student to find
student_to_find = "Bob"

# Loop through the list to find the specific student
for index, student in enumerate(students):
    if student == student_to_find:
        print(f"Found {student_to_find} at index {index}")
        break
else:
    print(f"{student_to_find} not found in the list")